### ISSUE TITLE
Cannot run the file even after chmod +x uad_gui-linux

### ISSUE THREAD

**Issue by samuraikid0** [0x192/Universal-Android-Debloater#113]
**Describe the bug**
Cannot run the file even after chmod +x uad_gui-linux

**Expected behavior**
To open like when was .sh

**You have a solution?**
Maybe a .deb installer ?

**UAD log**
none

**Comment by 0x192** [comment]
chmod +x is no longer needed on Linux now that I use tarball (.tar.gz). The execution permission is no longer lost during Github Actions.

Since `v0.4`, the logs are located at [a standard location](https://docs.rs/dirs/latest/dirs/fn.cache_dir.html). On Linux it is `/home/<user>/.cache/uad/`. Upload it. I can't help otherwise :)

**Note:**:  You can directly see the warnings and errors by launching UAD from the terminal. When something doesn't launch that the first thing to do!

**Comment by samuraikid0** [comment]
Ok i manage to execute it, ill close the issue

Presuming the file is already executable, you can simply type `./uad_gui-linux`

If it isn't executable yet, you can set the executable bit with `sudo chmod +x ./uad_gui-linux` and then run the above command.

FAQ confused me 
Thanks once again !!
