### ISSUE TITLE
Oppo Reno 3A CPH2013 won't show lock screen

### ISSUE THREAD

**Issue by JapanYoshi** [0x192/universal-android-debloater#158]
**Your phone**: Oppo Reno 3A, Japanese version, CPH2013

**Describe the issue**
After debloating my phone, its lock screen won't stay on for longer than a few seconds. The background sporadically fades in and cuts to black. No text is displayed.
If I long press the Power button, a big blank dialog box is shown; it gets bumped up and down as the lock screen fades in and cuts out.

[Video of the phenomenon](https://www.youtube.com/watch?v=sYGftc3a_Ro)

Not exactly a boot loop, since the boot appears to complete. It's just the lock screen that refuses to display correctly and accept inputs.

**You have a solution?**
I have no solution so far. Since I can boot into Recovery Mode, I think my only option left at this point is to flash firmware.

**UAD log**
March 7: I deactivated some packages that I didn't want. [UAD_20220307.log](https://github.com/0x192/universal-android-debloater/files/8204863/UAD_20220307.log)
March 8 (today): I attempted to reboot my phone and first encountered this issue. I then connected the un-booting phone to my computer and tried to restore all the packages I deactivated the day before, since I had set the phone up to automatically grant permission for my computer to debug via USB, and UAD seemed to give me the option. [UAD_20220308.log](https://github.com/0x192/universal-android-debloater/files/8204864/UAD_20220308.log)

**Comment by runninghamster0** [comment]
I've had the same problem on my Oppo A52. It turned out the issue was the ColorOS weather app `com.coloros.weather2`.
Removing it causes the lockscreen issue. Only way to fix it is to do a factory reset.

**Comment by 0x192** [comment]
@runninghamster0
I don't understand why you needed to perform a factory reset if `com.coloros.weather2` was the problem? Restoring the package wasn't enough? 
By the way, can `com.coloros.weather.service` still be removed?

Maybe you had this issue because you had the weather widget on the lockscreen?

**Comment by JapanYoshi** [comment]
> I don't understand why you needed to perform a factory reset if `com.coloros.weather2` was the problem? Restoring the package wasn't enough?

I don't either. Oppo's ROM is scum.

> Maybe you both have this issue because you had the weather widget on the lockscreen?

I never even used or accessed the weather app. or weather widget. How dare you assume I'm that kind of plebeian.

**Comment by runninghamster0** [comment]
> @runninghamster0 I don't understand why you needed to perform a factory reset if `com.coloros.weather2` was the problem? Restoring the package wasn't enough? By the way, can you confirm that `com.coloros.weather.service` can still be removed?
> 
> Maybe you both have this issue because you had the weather widget on the lockscreen?

Sorry for the late reply, I wanted to test the packages before I posted back. For reference, I am not signed into an OEM Oppo account and do not use the in-built weather widget either.
I removed `com.coloros.weather2` and the phone still functioned without issues, even after rebooting. I then tested removing `com.coloros.weather.service` and rebooted and that's when the lockscreen issue started appearing. It seems the culprit is the weather service and not the app itself (which is safe to remove).

Restoring the `com.coloros.weather.service` app immediately fixes the lockscreen issue, so yes, restoring the package does work. Resorting to a factory reset was an oversight on my part.

**Comment by JapanYoshi** [comment]
> Restoring the `com.coloros.weather.service` app immediately fixes the lockscreen issue, so yes, restoring the package does work. Resorting to a factory reset was an oversight on my part.

Restosing ALL apps didn’t fix the issue on my end.

**Comment by runninghamster0** [comment]
> > Restoring the `com.coloros.weather.service` app immediately fixes the lockscreen issue, so yes, restoring the package does work. Resorting to a factory reset was an oversight on my part.
> 
> Restoring ALL apps didn’t fix the issue on my end.

I'm not too sure then.

For me, as soon as I removed the weather service application, the lock screen started showing the flashing issue.

I then restored the package and it seemed to fix itself. I didn't reboot at all within these steps so that may be the differing factor?

Regardless, I think we can agree that the weather service package should not be removed.
