### ISSUE TITLE
Packages needed for Samsung DeX 

### ISSUE THREAD

**Issue by kimonm** [0x192/Universal-Android-Debloater#168]
Can anyone tell me the (minimum) set of apks required for DEX to work on SM-991GU1 (Samsung S21 5G US model)?
I've restored:
com.samsung.desktopsystemui
com.sec.android.app.desktoplauncher
com.sec.android.desktopmode.uiservice
com.sec.android.app.dexonpc

The bottom taskbar is still missing, however. Thanks.

**Comment by 0x192** [comment]
`com.sec.android.desktopcommunity` ?

[Please upload your logfile](https://github.com/0x192/universal-android-debloater/wiki/FAQ#where-are-the-logfiles). I need to know what package you removed.

**Comment by kimonm** [comment]
Thanks for the quick response, but com.sec.android.desktopcommunity doesn't seem to exist. I should have mentioned, that the phone is running Android 12 with Mar 1 security patch, and One UI 4.0

Is there a way to generate a new log file? I have several from trying to add and subtrack .apks. Attached is the original debloat
[UAD_20220203.log](https://github.com/0x192/universal-android-debloater/files/8329194/UAD_20220203.log)
.

**Comment by 0x192** [comment]
Sorry for the late reply. The

Mhm... honestly I don't know. You are better placed to try and see what package is needed. You can try by dichotomy: 

1) Restore all the Samsung packages (`Oem` list) and check your issue is fixed
2) Uninstall the first half of the `Recommended` list. 
3) Check if you have the issue
4) If you have the issue, you know the culprit is in this half. Restore the packages and uninstall the half of this set. Go back to 3
If you don't have the issue, you know the culprit is in the other half. You know what to do...

Keep me informed so I can update the debloat list for everyone else :slightly_smiling_face:
