### ISSUE TITLE
UAD GUI files download/open as TextEdit documents on Mac

### ISSUE THREAD

**Issue by EveryGoodUsernameIsTaken** [0x192/Universal-Android-Debloater#180]
Hi there. Homebrew and Android platform tools are installed, but each of the four MacOS UAD GUI files download/open as TextEdit documents. What am I missing?

If this app is anything like Szaki's "Xiaomi ADB/Fastboot Tools", I'm really looking forward to using it!

**Comment by 0x192** [comment]
Are you sure you downloaded the latest version (`v0.5`)? The problem you are facing was fixed in this release. 

The solution for older releases (but I don't recommend you to use an older release) :

-------
### Why the hell can't I launch this app on MacOS?

There is a bug in the Github Action I use ([upload-artifact](https://github.com/actions/upload-artifact/issues/38)) for automating the upload of all UAD releases that makes Linux and MacOS binaries to loose their executable permission. Putting them in a tarball (compressed `.tar.gz` archive) fix the issue and that's what I did for the Linux release.

There is no problem for the windows and Linux release. You can just double-clicking on it.

On MacOS you have to right click on the app and choose "Open" instead of double clicking on it. If this still doesn't work, open a terminal and add the executable permission like explained below.

```bash
chmod +x uad_gui-macos
```
**Note**: In the next release (`v0.5`), MacOS binary will also be archived in a tarball.

**Comment by EveryGoodUsernameIsTaken** [comment]
Yes, I'm referring to v0.5 obtained from the 'Releases' page. They open as TextEdit documents on both Monterey and Catalina.

I also tried v0.4.1 using right click/open and the terminal command, but these methods don't work either. Terminal command returns the following:

chmod: uad_gui-macos: No such file or directory

**Comment by 0x192** [comment]
> Yes, I'm referring to v0.5 obtained from the 'Releases' page

Oh! You're right! My bad there is an issue in the automatic Github release process. I'll fix this.

> chmod: uad_gui-macos: No such file or directory

Make sure you are in the same directory as UAD

**Comment by 0x192** [comment]
Fixed.

**Comment by EveryGoodUsernameIsTaken** [comment]
All good now, cheers.
