### ISSUE TITLE
Huawei P30 (ELE 29) not detected

### ISSUE THREAD

**Issue by EpicOddOtaku** [0x192/Universal-Android-Debloater#231]
**Describe the bug**
Huawei P30 (ELE 29) is not detected.

**Expected behavior**
It should automatically detect my phone.

**You have a solution?**
Put the uad_gui-windows.exe in the same folder as your platform-tools.

**UAD log**
Upload the logfile generated by UAD.
[UAD_20220519.log](https://github.com/0x192/universal-android-debloater/files/8725178/UAD_20220519.log)

**Comment by 0x192** [comment]
> You have a solution?
Put the uad_gui-windows.exe in the same folder as your platform-tools.

This works because the OS will first try to find the adb binary in the current directory. However, it's better to add the adb directory directly to the PATH. 

The PATH is an environment variable that contains an ordered list of paths that your OS will search for executables when running a command. This means you'd no longer need to run UAD from the ADB directory and you could run ADB commands from everywhere. 

This is precisely what I ask to do in the README (which is a something you should... READ :upside_down_face:)

> Download [android platform tools](https://dl.google.com/android/repository/platform-tools-latest-windows.zip) and unzip it somewhere. [Add the folder to your PATH](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/).
>
> https://github.com/0x192/universal-android-debloater#how-to-use-it
