### ISSUE TITLE
How to start it?

### ISSUE THREAD

**Issue by lakimakromedia** [0x192/Universal-Android-Debloater#243]
I dont get this github, sometime there is ready aplication sometimes like here just code, how to start this?

**Comment by AnonymousWP** [comment]
> I dont get this github, sometime there is ready aplication sometimes like here just code, how to start this?

https://github.com/0x192/universal-android-debloater#how-to-use-it

**Comment by novoid** [comment]
The README does explain a lot of things. It does not explain:

- search for the topmost(?) "Assets" on https://github.com/0x192/universal-android-debloater/releases and click it to open up the list of downloadable files
- unpack the file if it ends with "tar.gz" + maybe how
- what to do if ADB is no in the path (there is no `--help` CLI parameter of this tool)

**Comment by 0x192** [comment]
> The README does explain a lot of things. It does not explain: [...]

This is because if a user can't figure it out, it probably means that they shouldn't use this software. I say this without being mean.

I could make sure UAD download ADB on Windows if it doesn't find it. I'll do this on day when the software will be a bit more mature but for now, I'm fine with preventing some very beginner users from using this software. UAD will be better and more noob-friendly in the future. It just needs more time.

> what to do if ADB is no in the path

The README redirects to an article explaining how to add a directory to the PATH.
