### ISSUE TITLE
Does this not work with ADB over Wireless?

### ISSUE THREAD

**Issue by Jaladhjin** [0x192/Universal-Android-Debloater#287]
**Describe the bug**
I'm connected via ADB over Wireless & can execute commands & even Scrcpy into my device but this application doesn't seem to detect a device found.

Here's some small proof my device is in fact connected & recognized:
adb devices
List of devices attached
192.168.1.172:34649     device

Device is a Samsung Note 10+

I'd be very grateful if a solution were found & happy to test builds because I never "wire in" anything as often as I can avoid it ha.

**Expected behavior**
I expect the device to be found & this application to perform as expected

**You have a solution?**
I unfortunately do not I suspect it's some flag to allow ADB over Wireless to be recognized as well

**UAD log**
Upload the logfile generated by UAD.
[UAD_20220703.log](https://github.com/0x192/universal-android-debloater/files/9034261/UAD_20220703.log)

**Comment by 0x192** [comment]
According the logfile. UAD doesn't even succeed to launch `adb`. Are you sure `adb` is in your PATH? 

Can you run `adb` anywhere from your computer or do you have to go in the `platform-tools` directory? I suspect you are on Windows. So by adding adb to your path I mean [adding the platform-tools directory to your PATH](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/).

It's in the [How to use section of the README](https://github.com/0x192/universal-android-debloater#how-to-use-it)

This may not fix the underlying problem because I actually never tested to use UAD with wireless ADB but it should work I think.

**Comment by 0x192** [comment]
I had the opportunity to test wireless ADB with UAD and it works just fine. 

As mentionned in my last comment, your problem is that `adb` is not in your PATH
