### ISSUE TITLE
Hello, I want to help!

### ISSUE THREAD

**Issue by 443Port** [0x192/Universal-Android-Debloater#289]
Hi! This project looks cool. I wanna help you guys make it but I don't really have experience in coding :c 
Maybe I could do like translation to Polish? Cause that's my native.
Anyway you can contact me on Discord: XPort#7542.

**Comment by 0x192** [comment]
Thanks for wanting to help. That's nice of you! :slightly_smiling_face: 

>  Maybe I could do like translation to Polish? Cause that's my native.

The translations are unfortunately not maintainable in the long run because all the application descriptions are written in English. It would be really hard to maintain knowledge base in multiple language at the moment. Maybe one day but I doubt it.

> I don't really have experience in coding :c

The main challenge of this project is documenting apps. It requires some technical skills though. But you can still try to document some packages not listed in UAD.

**Comment by 443Port** [comment]
> But you can still try to document some packages not listed in UAD.

I could try! Thanks for telling me.

**Comment by 443Port** [comment]
I'm so sorry for reopening this. Once this project is ready to be translated we can use: https://crowdin.com

**Comment by triallax** [comment]
My two cents: if UAD ever adds translation support, I think it should use a free and open-source translation platform, such as Weblate, and not a proprietary platform, such as Crowdin.

**Comment by 443Port** [comment]
> My two cents: if UAD ever adds translation support, I think it should use a free and open-source translation platform, such as Weblate, and not a proprietary platform, such as Crowdin.

Oh I only knew Crowdin XD
