### ISSUE TITLE
Trying to download remote UAD list ... panicked ...  Error("unknown variant `Exert`)

### ISSUE THREAD

**Issue by t-legiaw** [0x192/Universal-Android-Debloater#295]
**Describe the bug**
UAD stopped working as expected. For example all package descriptions are empty

**Expected behavior**
normal operation (as a few days before)

**UAD log**
the console output shows a line saying
```
panicked at 'Unable to parse: Error("unknown variant `Exert`, expected one of `All`, `Recommended`, `Advanced`, `Expert`, `Unsafe`, `Unlisted`", line: 7209, column: 22)', src/core/uad_lists.rs:214:60
```

**Comment by t-legiaw** [comment]
note:  I think I found the culprit in the downloaded/cached ~/.cache/uad/uad_lists.json file. See diff below ...

```
--- a/uad_lists.json  2022-07-06 21:02:17.087223190 +0200
+++ b/uad_lists.json  2022-07-06 21:02:52.527162245 +0200
@@ -7202,15 +7202,15 @@
   {
     "id": "com.android.proxyhandler",
     "list": "Aosp",
     "description": "Handles proxy config.\nSafe to remove if you don't use a proxy.",
     "dependencies": null,
     "neededBy": null,
     "labels": null,
-    "removal": "Exert"
+    "removal": "Expert"
   },
   {
     "id": "com.android.quicksearchbox",
     "list": "Aosp",
     "description": "Google quick search box.\n",
     "dependencies": null,
     "neededBy": null,
```

**Comment by DoinStuff35** [comment]
[UAD_20220706.log](https://github.com/0x192/universal-android-debloater/files/9057459/UAD_20220706.log)

Not sure if connected to this Problem:

**Describe the bug**
Stuck on "Downloading latest UAD lists from Github." --> Clicking "No Internet" --> Phone detected but no packages are listed. json file can be found in C:\Users\[MYUSERNAME]\AppData\Local\uad (uad_lists.json; 745kb).

**Expected behavior**
normal operation (as a few days before). Used 0.5.0, now on 0.5.1, same Problem.

**UAD log**
see attached log.

**Comment by 0x192** [comment]
Thanks for the report. I've just fixed the issue.

I really need to develop a proper test suite for the debloat list.
