### ISSUE TITLE
UAD GUI not downloading new UAD lists

### ISSUE THREAD

**Issue by wilfredocamacho** [0x192/Universal-Android-Debloater#335]
**Describe the bug**
UAD GUI is stuck at "Downloading latest UAD lists from GitHub. Please wait...". 

**Expected behavior**
I expect the GUI to continue with its normal behavior after downloading the lists.

**You have a solution?**
No, I do not.

**UAD log**
Sadly I don't know where it is located...
EDIT: I found the log:

2022-08-05 19:08:59 DEBUG [src\core\update.rs:178] Checking for UAD update
2022-08-05 19:08:59 WARN  [src\gui\mod.rs:102] Trying to download remote UAD list
2022-08-05 19:09:29 DEBUG [src\core\update.rs:178] Checking for UAD update
2022-08-05 19:09:29 DEBUG [src\core\update.rs:178] Checking for UAD update
2022-08-05 19:09:31 DEBUG [src\core\update.rs:178] Checking for UAD update
2022-08-05 19:09:32 DEBUG [src\core\update.rs:178] Checking for UAD update
2022-08-05 19:09:34 ERROR [src\core\utils.rs:162] Can't open the following URL: 

[UAD_20220805.log](https://github.com/0x192/universal-android-debloater/files/9273942/UAD_20220805.log)

**Comment by Wilker-uwu** [comment]
output from running the program in a Bash terminal suggests me that it's a syntax error on the file.

```
022-08-05 21:33:51 WARN  [src/gui/mod.rs:102] Trying to download remote UAD list
thread '<unnamed>' panicked at 'Unable to parse: Error("invalid type: sequence, expected a string", line: 2014, column: 16)', src/core/uad_lists.rs:214:60
```

from the line in question:
https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json#L2014

**Comment by g-k-m** [comment]
The entire program doesn't work as all installed apps just get sorted into Unlisted due to this error and is thus useless

**Comment by YoranSys** [comment]
I created a pull request: https://github.com/0x192/universal-android-debloater/pull/336

The json is broken here:  https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json#L19175

**Comment by ll0r3nt3** [comment]
Same

**Comment by Danish319** [comment]
Facing the same issue. Is there a temporary workaround please?

**Comment by ll0r3nt3** [comment]
This is the bad thing about having a project on this site, that without internet or if it does not establish a connection correctly, the program becomes useless, I wish I could make another "offline" program

**Comment by YoranSys** [comment]
Maybe we can add an option to import the json for offline usage or checking the json before making a PR

**Comment by ll0r3nt3** [comment]
> Maybe we can add an option to import the json for offline usage or checking the json before making a PR

It would be fantastic, today I used the program in offline mode, you click "no internet connection" and then reload and the packages are loaded, although without a description obviously

**Comment by Wilker-uwu** [comment]
> Maybe we can add an option to import the json for offline usage or checking the json before making a PR

both is good. there should be a feature where you get pointed to the file itself to fix any mistakes, replace with another, *and* a failsafe feature where you get to load previous file versions from commits.

###### and also syntax check before replacing the file

**Comment by 101pranjal101** [comment]
Fix this issue please, i just love this debloater

**Comment by stephendt** [comment]
Chiming in to say that I'm also experiencing this issue.

**Comment by gerega** [comment]
Same issue still here!

Interestingly, version 0.4.1 works fine! 0._5 and 0.5.1 do not. Most likely because of the new listupdate feature from 0.5 and above.

Cleaned ~/.cache/uad 
Cleaned ~/.config/uad

When opening ./uad_gui-linux - last two lines look promising only!

`[itsme@darkside Downloads]$ ./uad_gui-linux\ \(1\)`

`2022-08-07 11:59:22 WARN  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.12.4/src/gles/egl.rs:696] Re-initializing Gles context due to Wayland window MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0`

`2022-08-07 11:59:22 WARN  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.12.4/src/gles/adapter.rs:450] Detected skylake derivative running on mesa i915. Clears to srgb textures will use manual shader clears.`

`2022-08-07 11:59:23 WARN  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.12.4/src/gles/egl.rs:696] Re-initializing Gles context due to Wayland window`

`2022-08-07 11:59:23 WARN  [src/gui/mod.rs:102] Trying to download remote UAD list`

`2022-08-07 11:59:23 WARN  [/home/runner/.cargo/git/checkouts/winit-57d3141eaf559308/02a1238/src/platform_impl/linux/wayland/seat/pointer/mod.rs:115] Failed to set cursor to Default thread '<unnamed>' panicked at 'Unable to parse: Error("invalid type: sequence, expected a string", line: 2014, column: 16)', src/core/uad_lists.rs:214:60 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

The log file does not show any errors.

P.S. Dont get it how to add a nice code snippet. This ` ` code breaks it all!

**Comment by K3RN3L32** [comment]
Please fix the goddamn semicolon, I beg you.

**Comment by ptaszkie** [comment]
Workaround: run program, go to cached folder (select in right upper corner About -> Locate the logfiles), open uod_lists.txt and fix double "" at the end on line 19175. Click "No internet?" in tab "Apps". It works for me :)

**Comment by 0x192** [comment]
This is the second time this kind of issue happen. I'm really sorry guys! I took a day off yesterday and I've just seen this absurdly lame bug.

I've already added a [test for checking the json](https://github.com/0x192/universal-android-debloater/blob/main/src/core/uad_lists.rs#L257) but like an idiot I forgot to add it in Github Actions.

This won't happen again!

**Comment by wilfredocamacho** [comment]
> This is the second time this kind of issue happen. I'm really sorry guys! I took a day off yesterday and I've just seen this absurdly lame bug.
> 
> I've already added a [test for checking the json](https://github.com/0x192/universal-android-debloater/blob/main/src/core/uad_lists.rs#L257) but like an idiot I forgot to add it in Github Actions.
> 
> This won't happen again!

Thank you, it works now :)

**Comment by K3RN3L32** [comment]
Cimer 👍
