### ISSUE TITLE
Persist application settings 

### ISSUE THREAD

**Issue by onguarde** [0x192/Universal-Android-Debloater#357]
The settings don't seem to be saved when the application is closed. This is dangerous because I re-opened the application thinking the checkbox above WAS enabled. I will lose the ability to restore, if I hadn't checked that box.

![image](https://user-images.githubusercontent.com/681355/185731099-9838dce7-fd72-470a-8b99-8503cfdcefdf.png)

According to #44, this should already be implemented. Perhaps it's a regression?

Btw, the checkbox should be set to ON by default, any reason why it's not?

I'm using the openGL latest 0.51 version.

**Comment by 0x192** [comment]
The config file [currently](https://github.com/0x192/universal-android-debloater/blob/main/CHANGELOG.md#added-2) only keeps the `Theme` value. This is not ideal but I didn't want to add the others settings before I implement unique settings for each phone.

I would point out that the category name of those settings explicitly says that those are not persistent (look at your screenshot :wink:)

For example, if you tick `clear and disable...` for your Android 9 phone and then plug another phone with `Android 4.4`, there will be a problem because you can't disable an app on Android 4.4. You have to use `adb pm block / unblock` which is the equivalent of an `adb pm uninstall`.

I'll prefer each phone to have its own settings.

Anyway, that's a feature for the next release!

 ----
> This is dangerous because I re-opened the application thinking the checkbox above WAS enabled. I will lose the ability to restore

Uninstalling an app will not prevent you to restore it. The defaults settings are pretty smart. You can always restore an application. [Take a look at the adb commands used](https://github.com/0x192/universal-android-debloater/wiki/FAQ#what-are-the-adb-commands-used-by-uad)
