### ISSUE TITLE
Uninstalling com.xiaomi.simactivate.service breaks receiving SMS

### ISSUE THREAD

**Issue by thanhminhmr** [0x192/Universal-Android-Debloater#373]
**Your phone**: Xiaomi 11 Lite 5G NE (MIUI Global 13.0.5 Stable)

**Describe the issue**
Uninstalling `com.xiaomi.simactivate.service` breaks receiving SMS.

**How do you know this?**
- I send a test SMS from another phone, the Xiaomi phone receives it normally.
- I uninstall this package, reboot the Xiaomi phone, and then send a test SMS from another phone. This time, no SMS notification, nothing in the inbox. The SMS simply vanished (or never being received).
- Reinstall the package, reboot. Send another test SMS, voila, it receive the SMS just fine.
(Note that I'm from Vietnam and I'm using Mobifone. There is a chance that this is a carrier specific issue.)

**You have a solution?**
This package description should have a warning like "Do not touch this package if you want to receive SMS."

<details>
<summary>Screenshot</summary>

![IMG_20220903_112139_2](https://user-images.githubusercontent.com/31412085/188255783-e49a92ed-a651-41e2-8df8-d4df136bf7cb.jpg)
</details>

**Comment by 0x192** [comment]
Mhm that's weird because `com.xiaomi.simactivate.service` is a SIM authentication process to access exclusive features **in certain MIUI applications**. Removing this service should not have prevented you to send messages. I already have tested this on several phones.

> send a test SMS from another phone

Does this *other phone* was a non-debloated Xiaomi phone? Maybe it has to do with Mi Messaging? (**Settings** -> **System Apps** -> **Messaging**)

> **Mi Message**: MIUI users can send text messages to other Mi users using an internet connection. Messaging service routes your text messages via a server based in China to the recipient.

Can you also see if you still receive an acknowledgement receipt (you can enable this feature in your SMS settings app) when you remove `com.xiaomi.simactivate.service`?

I assume from your screenshot that you are using [Simple SMS Messenger](https://f-droid.org/fr/packages/com.simplemobiletools.smsmessenger/) on your Xiaomi 11. That's a good choice but can you try to put the MI Messaging app back as the default SMS app just to see if that can solve the problem?

**Comment by ll0r3nt3** [comment]
no for me, all sms work.

maybe smspush?

**Comment by thanhminhmr** [comment]
Ok maybe it is not the `com.xiaomi.simactivate.service` that cause the SMS problem. I turned off battery saver and turn on auto start on SMS app and now I can receive SMS normally. Maybe MIUI battery saver block the app from receiving SMS? Anyway, this problem needs some more investigation I guess.
(and yes, I use [Simple SMS Messenger](https://f-droid.org/fr/packages/com.simplemobiletools.smsmessenger/)!)

**Comment by ghost** [comment]
It doesn't break the sms service. I have this package uninstalled for more than year and never had a problem. It is because you are using 3rd party app and xiaomi applies battery saving features for the all 3rd party apps.
Check this: 
https://dontkillmyapp.com/xiaomi

**Comment by thanhminhmr** [comment]
> Ok maybe it is not the `com.xiaomi.simactivate.service` that cause the SMS problem. I turned off battery saver and turn on auto start on SMS app and now I can receive SMS normally. Maybe MIUI battery saver block the app from receiving SMS? Anyway, this problem needs some more investigation I guess. (and yes, I use [Simple SMS Messenger](https://f-droid.org/fr/packages/com.simplemobiletools.smsmessenger/)!)

Apparenly this is the solution for my problem. Closing the issue as solved.
