### ISSUE TITLE
What is an OEM account?

### ISSUE THREAD

**Issue by jult** [0x192/Universal-Android-Debloater#385]
Just a strange question, but what exactly *is* an OEM account on an android phone? You state to remove or disable them from the settings?

**Comment by AnonymousWP** [comment]
An OEM account is something like a Samsung account or OnePlus account on your Samsung or OnePlus phone, let's say. They can be used to collect and link data (e.g. to save your IMEI on your account) or gather community points on forums for example (in case of OnePlus). You can also check your account details and they're usually a separate setting (which is why it's an APK that can be disabled).

**Comment by 0x192** [comment]
To complete the answer of @AnonymousWP 

Most big manufacturers (i.e [OEM](https://en.wikipedia.org/wiki/Original_equipment_manufacturer)) offer some cloud storage, access to services (e.g. theme stores, payment functionality, alternative app stores), and/or the ability to sync your data if you create an account.

For instance, on a Samsung phone: https://www.samsung.com/us/support/answer/ANS00085942/
