### ISSUE TITLE
UAD not recognizing my Realme Phone

### ISSUE THREAD

**Issue by Ajithkumar7925** [0x192/Universal-Android-Debloater#418]
Universal android debloater not recognizing my Realme GT Neo 3T. I tried all the ways but not recognizing. Tell me how to fix
![Universal Android Debloater 21-10-2022 12_20_36](https://user-images.githubusercontent.com/72341402/197131445-c3b4db53-1453-450b-b487-51331dd6bf19.png)

**Comment by AnonymousWP** [comment]
> Universal android debloater not recognizing my Realme GT Neo 3T. I tried all the ways but not recognizing. Tell me how to fix ![Universal Android Debloater 21-10-2022 12_20_36](https://user-images.githubusercontent.com/72341402/197131445-c3b4db53-1453-450b-b487-51331dd6bf19.png)

Did you follow these steps? https://github.com/0x192/universal-android-debloater#how-to-use-it

**Comment by meeeeeeeeeeeeeeee** [comment]
I'm having the same problem with my google pixel 3a, adb devices shows it is connected and I can use adb shell but this program says no devices or emulators found.

I updated adb and tried again but that didn't fix anything, I'm using the opengl version because I don't have any graphics cards that support vulcan and the computer I'm using is a gaming laptop with windows 7 professional SP1 64 bit.

**Comment by kxwish** [comment]
Same issue with my Motorola Moto E 2020. ADB works fine, I've installed all the drivers yet I still am unable to use the Debloater

**Comment by bloodSilver19** [comment]
I experieced that issue cuz i forgot to put the exe file in the same folder as the adb.exe so if you haven't done that maybe tht will work.

**Comment by olielvewen** [comment]
I have the issue with a Redmi Note 9 Pro on Manjaro with the version 0.5.1. And adb in CLI works fine.

**Comment by RonP3B** [comment]
> I experieced that issue cuz i forgot to put the exe file in the same folder as the adb.exe so if you haven't done that maybe tht will work.

Thanks, that was my problem.

**Comment by 0x192** [comment]
You all didn't read the [`HOW TO USE`](https://github.com/0x192/universal-android-debloater#how-to-use-it)  section of the README... :imp:

UAD can't find `adb` if the binary is not in the PATH (or in the same directory as UAD)


One day, when UAD will be more mature, I'll make sure it auto downloads adb at launch if not found. 

I don't do it now because it prevents some non-tech-savvy to use UAD. If someone doesn't succeed to launch UAD this probably mean they should not use the software. If you don't know what you are doing... stop. I don't want you to break your phone. :slightly_smiling_face:

**Comment by bloodSilver19** [comment]
> You all didn't read the [`HOW TO USE`](https://github.com/0x192/universal-android-debloater#how-to-use-it) section of the README... imp
> 
> UAD can't find `adb` if the binary is not in the PATH (or in the same directory as UAD)
> 
> One day, when UAD will be more mature, I'll make sure it auto downloads adb at launch if not found.
> 
> I don't do it now because it prevents some non-tech-savvy to use UAD. If someone doesn't succeed to launch UAD this probably mean they should not use the software. If you don't know what you are doing... stop. I don't want you to break your phone. slightly_smiling_face

Dont know wtf you talking about. I added it the android platform tools to PATH at the time and it weren't working. And I know I added it right because I tested adb in cmd and is was being picked up, even saw my device. UAD just couldnt pick up adb for whatever reason.
