### ISSUE TITLE
Make Mac GUI executable?

### ISSUE THREAD

**Issue by skylarkenvoy** [0x192/Universal-Android-Debloater#456]
Can you either please make the make GUI executable? I eventually [found through a forum search](https://forum.xda-developers.com/t/2022-07-03-v0-5-1-universal-android-debloater.4069209/page-11#post-86697133) that I had to use the chmod command to make the GUI executable on my Mac, but could this be enabled by default? Or at least add a note to the Mac line of the FAQ?

**Comment by itsOwen** [comment]
I think there is already a mac gui executable

**Comment by skylarkenvoy** [comment]
There are Mac OS GUI files but none of them are executable out of the box, after downloading and unzipping. Mac OS loads each of them as a text file in TextEdit. I had to use the chmod command in Terminal to make it executable. It took me ages to find that solution too!

**Comment by itsOwen** [comment]
I am on mac as well you need to check the release tab you will see a mac executable just double click and you will see a gui simply select what you want to remove done.

**Comment by rezinate-92** [comment]
Unsubscribe

**Comment by rezinate-92** [comment]
Unsubscribe

**Comment by 0x192** [comment]
MacOS releases have the executable permission since `v0.5`. I've just checked again. 

Be sure to download the last version (`0.5.1`)

https://github.com/0x192/universal-android-debloater/releases

![image](https://user-images.githubusercontent.com/55300518/208252340-699d6dde-b3de-4238-b7a5-a51a411b5e16.png)
