### ISSUE TITLE
Build fails on (my) Debian

### ISSUE THREAD

**Issue by atrent** [0x192/Universal-Android-Debloater#528]
I tried to compile it unde Debian (bookworm, kernel 5.19.0-2-amd64), I got this error:

```
   Compiling serde_json v1.0.91
   Compiling toml v0.5.10
   Compiling smithay-client-toolkit v0.16.0
   Compiling wgpu-hal v0.14.1
   Compiling iced_graphics v0.6.0 (https://github.com/iced-rs/iced.git#18552f96)
error[E0658]: generic associated types are unstable
  --> /home/atrentini/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/18552f9/graphics/src/image/storage.rs:12:5
   |
12 |     type State<'a>;
   |     ^^^^^^^^^^^^^^^
   |
   = note: see issue #44265 <https://github.com/rust-lang/rust/issues/44265> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `iced_graphics` due to previous error
warning: build failed, waiting for other jobs to finish...
```

I'm not familiar with the rust environment, can you suggest an action?

Thanks

**Comment by 0x192** [comment]
It's because the UAD version you are trying to build is based on Rust nightly and you have installed the stable toolchain. 

The good news is that you don't have to install Rust nightly because UAD is now based on Rust stable since 44fe67f. The [wiki page](https://github.com/0x192/universal-android-debloater/wiki#)) has been updated a bit early.

However I suggest you to wait a bit. There is a annoying bug in the `main` branch. A new release  (`v0.6`) will be out this weekend.

**Comment by atrent** [comment]
will do, thanks
