### ISSUE TITLE
glutin dependency error

### ISSUE THREAD

**Issue by Raviu56** [0x192/Universal-Android-Debloater#56]
Hey when I run `cargo build` I get the following error:

```
    Updating git repository `https://github.com/iced-rs/glutin`
error: failed to get `glutin` as a dependency of package `iced_glutin v0.2.0 (https://github.com/hecrj/iced.git#569aff33)`
    ... which satisfies git dependency `iced_glutin` (locked to 0.2.0) of package `iced v0.3.0 (https://github.com/hecrj/iced.git#569aff33)`
    ... which satisfies git dependency `iced` (locked to 0.3.0) of package `uad_gui v0.3.0 (/tmp/universal-android-debloater)`

Caused by:
  failed to load source for dependency `glutin`

Caused by:
  Unable to update https://github.com/iced-rs/glutin?rev=2564d0ab87cf2ad824a2a58733aebe40dd2f29bb#2564d0ab

Caused by:
  object not found - no match for id (2564d0ab87cf2ad824a2a58733aebe40dd2f29bb); class=Odb (9); code=NotFound (-3)
  ```

**Comment by 0x192** [comment]
Did you change the `Cargo.toml`? I don't have any issue on my side (I've just tested it after a `cargo update`) and I don't see how you could have this kind of issues without modifying the manifest.

**Comment by OrrellElectrics** [comment]
Same for me from AUR package: https://aur.archlinux.org/packages/universal-android-debloater/

error: failed to get `glutin` as a dependency of package `iced_glutin v0.2.0 (https://github.com/hecrj/iced.git#569aff33)`
    ... which satisfies git dependency `iced_glutin` (locked to 0.2.0) of package `iced v0.3.0 (https://github.com/hecrj/iced.git#569aff33)`
    ... which satisfies git dependency `iced` (locked to 0.3.0) of package `uad_gui v0.3.0 (/home/gary/universal-android-debloater/src/universal-android-debloater-0.3)`

Caused by:
  failed to load source for dependency `glutin`

Caused by:
  Unable to update https://github.com/iced-rs/glutin?rev=2564d0ab87cf2ad824a2a58733aebe40dd2f29bb#2564d0ab

Caused by:
  object not found - no match for id (2564d0ab87cf2ad824a2a58733aebe40dd2f29bb); class=Odb (9); code=NotFound (-3)
==> ERROR: A failure occurred in prepare().
    Aborting...

**Comment by 0x192** [comment]
I really can't reproduce the issue and I run Archlinux too.

I tried a fresh build: 
1) `git clone git@github.com:0x192/universal-android-debloater.git`
2) `cargo build`

No error...

Could it be some cache issues?
