### ISSUE TITLE
Panick 

### ISSUE THREAD

**Issue by eperitus** [0x192/universal-android-debloater#57]
After building this project with rustc on an M1 Mac with Terminal in Rosetta mode, I get the following error when trying to run the uad binary:

```
% RUST_BACKTRACE=1 ./uad        
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', ./build.rs:4:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: core::result::Result<T,E>::unwrap
   4: build::main
   5: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Any suggestions?  Am I doing something wrong?

**Comment by 0x192** [comment]
I don't know why `build.rs` is panicking when trying to find the target platform. What you can do is completely remove the `build.rs` file. It is no longer needed since I've been using the MSVC toolchain for Windows builds.*

EDIT: You can do a `git pull` to fix the issue. I've removed the file upstream.
