### ISSUE TITLE
How do I lauch this app, noob level

### ISSUE THREAD

**Issue by Finebouche** [0x192/Universal-Android-Debloater#61]
Hello, 
I am using mac. I have adb installed, debuging mode on device as well. 

After downloading the uad_gui-macos I haven't been able to launch the app from the "How to use it" section ? 

How exactly do I launch the app ?  What command do I use ? 

Thanks for any help

**Comment by 0x192** [comment]
There is a bug in the Github Action I use ([upload-artifact](https://github.com/actions/upload-artifact/issues/38)) for automating the upload of all UAD releases that makes GNU/Linux and MacOS binaries to loose their executable permission.

On MacOS you can right click on the app and choose "Open" instead of double clicking on it. This should launch UAD.

On Linux you have to add the exectuable permission:
```
chmod +x uad_gui-linux
```

You are not the first person having trouble to launch the app. I will update the FAQ. 
**EDIT**: [Done](https://github.com/0x192/universal-android-debloater/wiki/FAQ)

**Comment by Finebouche** [comment]
Thanks ! 

`chmod +x uad_gui-linux`

did the trick on macos as well
