### ISSUE TITLE
Usage of pm hide and pm block on Android KitKat and Lollipop

### ISSUE THREAD

**Issue by sbechet** [0x192/Universal-Android-Debloater#63]
If you've Android KitKat or above and do not have root access, use adb in PC to execute this command:

```
adb shell pm block PACKAGE         # for Android KitKat
adb shell pm hide  PACKAGE         # for Android Lollipop only
adb shell pm disable-user PACKAGE  # alternative to `pm hide`; for Android Lollipop and above; this works just like disabling an app through Settings app
```
To reinstate the app:

```
adb shell pm unblock PACKAGE   # for Android KitKat
adb shell pm unhide PACKAGE    # for Android Lollipop and only if you used `pm hide` earlier
adb shell pm enable PACKAGE    # for Android Lollipop and above
```

[source](https://android.stackexchange.com/questions/56620/enable-and-disable-system-apps-via-adb)

**Comment by 0x192** [comment]
Thanks for the heads-up ! 

So, from the [android Stackexchange discussion](https://android.stackexchange.com/questions/56620/enable-and-disable-system-apps-via-adb) it seems that:
-  `pm disable-user` doesn't exist on Android KitKat and below (which is weird because I recall using it on a very old phone)
-  `pm block`/`pm unblock` can be used for Android KitKat (4.4)
- `pm hide` only exists for Lollipop

I also wonder about the usefulness of `pm hide` is when you can use`pm-disable-user` instead (for Android 5+)

I'll go through the AOSP source code to verify all of this.

**Comment by 0x192** [comment]
Diving into the source code was interesting.

**For easier reference: https://github.com/0x192/universal-android-debloater/wiki/ADB-reference**
