### ISSUE TITLE
Cannot find the connected device

### ISSUE THREAD

**Issue by CapoFantasma97** [0x192/universal-android-debloater#732]
**Describe the bug**
The program fails to detect the connected devices. Tested on OnePlus 7 Pro and Samsung Galaxy Tab S7+.

The devices are correctly detected on other ADB tools (e.g. ["Tool All In One"](https://toolaio.tk/) by Mauronofrio has no problem detecting them immediately and uninstalling APKs remotely).

**UAD log**
[UAD_20230510.log](https://github.com/0x192/universal-android-debloater/files/11436963/UAD_20230510.log)

![immagine](https://github.com/0x192/universal-android-debloater/assets/9368910/2dd2dec1-cc1f-4a87-bd76-20a104d459f5)

**Comment by CrafterNova** [comment]
Same issue on windows 10 64 bit, connecting with Redmi 9 Power, Android 12

**Comment by plexxman** [comment]
I had the same issue and inspecting the log file (mine was identical to yours) it's complaining because UAD couldn't find an ADB executable. So I downloaded Minimal ADB portable, extracted in one folder, copy/pasted UAD executable to the same folder where I extracted ADB and Voilà! It worked.

Minimal ADB: https://forum.xda-developers.com/t/tool-minimal-adb-and-fastboot-2-9-18.2317790/

Attached screenshot of minimal ADB and UAD in the same folder.
![image](https://github.com/0x192/universal-android-debloater/assets/17521576/2241c4d7-d4b1-4f61-a0e4-edff7b692ece)

**Comment by oMaikeru** [comment]
i still have the same issue even with portable adb

**Comment by Reinified** [comment]
> I had the same issue and inspecting the log file (mine was identical to yours) it's complaining because UAD couldn't find an ADB executable. So I downloaded Minimal ADB portable, extracted in one folder, copy/pasted UAD executable to the same folder where I extracted ADB and Voilà! It worked.
> 
> Minimal ADB: https://forum.xda-developers.com/t/tool-minimal-adb-and-fastboot-2-9-18.2317790/
> 
> Attached screenshot of minimal ADB and UAD in the same folder. ![image](https://user-images.githubusercontent.com/17521576/238124556-2241c4d7-d4b1-4f61-a0e4-edff7b692ece.png)

THANK YOU SO MUCH, sorry for the caps, but this made uad finally work for me.

**Comment by CapoFantasma97** [comment]
I solved it the day after I posted this issue by re-adding ADB to the PATH environment variables. I'm not sure why it wasn't there anymore. Other programs that run off ADB have their own portable ADB files so they didn't have the issue.
