### ISSUE TITLE
Theme packs and icons are safe to uninstall if the user doesnt use them.

### ISSUE THREAD

**Issue by ghost** [0x192/Universal-Android-Debloater#75]
packages like `com.android.theme.icon.teardrop`, `com.android.theme.icon.vessel` etc. are safe to remove if the user doesnt use them; you can add this to app descriptions.

**Comment by 0x192** [comment]
Yes. Correct.

There is a LOT of missing documentation for packages because I lack time. There is so much things to do. Improving the software itself is time consuming.

Making [Pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) will save me time compared to opening an issue. This is the kind of improvements a non-developer can do so that I can focus on solving code related problems or developing new features. :)

**Comment by ghost** [comment]
Well, I gotta learn how to make pull requests first :D
