### ISSUE TITLE
No Keyboard

### ISSUE THREAD

**Issue by kcstandefer** [0x192/Universal-Android-Debloater#91]
**Your phone**: \<Moto G7 Playl\>

**Describe the issue**
I uninstalled all of the suggested packages.  Afterward, I have no keyboard on my phone  

**You have a solution?**
I don't know how to fix

**UAD log**
Upload the logfile generated by UAD. You can hardly be helped without.
Where do I find the log file?

**Comment by lawson85** [comment]
The UAD log is stored in the same place ax UAD executable. You could export the uninstalled packages for us and we can diagnose issues

**Comment by kcstandefer** [comment]
Here is the log file

[uad.log](https://github.com/0x192/universal-android-debloater/files/7776371/uad.log)

**Comment by 0x192** [comment]
I guess you did not read the warning I put on the release page...

> Warning: This is still an alpha release. **Read carefully the description of the packages before removing them**. Parsing the old lists didn't 100% work. There are some quirks and some packages aren't in the appropriate recommendation list (Recommended, Advanced, Expert, Unsafe)

In any case, sorry for my late reply . Your problem is probably already fix by now and I hope you understood that you just had to list the uninstalled packages (by using the filter), find the keyboard app and click on the `Restore` button.

Keyboards being in the `Recommended` list is an issue already fixed. I just haven't published a the `v0.4` yet.

PS: I know why your log is empty. Every time your launch UAD, it overwrites the last logfile. I need to fix this silly behavior.

**Comment by kcstandefer** [comment]
I couldn't find any release that wasn't alpha.  I don't have any idea what
packages do or what they contain, so I just removed everything that was
suggested as safe to remove.
No, it isn't fixed.  But, I'm just going to factory reset it and trade it
for a different phone.  Thanks for responding.

Karen

**Comment by kcstandefer** [comment]
Actually, I can't even factory reset it because I can't enter my PIN# since
there is no keyboard.  so, if you could offer some help, that would be much
appreciated.

**Comment by 0x192** [comment]
> I couldn't find any release that wasn't alpha. I don't have any idea what packages do or what they contain, so I just removed everything that was suggested as safe to remove.

That's because there is no stable release yet. This is a big project and I don't have as much time to spend on it as I would like...

I'm sorry for what has happened to you. I don't want to sound rude but given your technical knowledge, you should have waited for a more mature release. I say this without any malice. I really hope I will be able to recommend this software to less tech-savy people but this isn't the case at the moment.

All the packages/apps in the `Recommended` list have a description. You just have to click on it. 

> I can't even factory reset it because I can't enter my PIN# since there is no keyboard.  so, if you could offer some help, that would be much appreciated
 
First, did you check the  _Always allow from this computer_ box when allowing USB debugging? (see [this image](https://www.wikihow.com/images/thumb/d/da/Install-ADB-Drivers-Step-13.jpg/v4-460px-Install-ADB-Drivers-Step-13.jpg.webp))

If you don't remember, just open a terminal and try to list all the uninstall packages of your phones. It should work if you checked that box:

```
./adb shell "pm list packages -s -u" > all_packages.txt
./adb shell "pm list packages -s" > installed_packages.txt
```
Upload the 2 files (` all_packages.txt` and `installed_packages.txt`  here and I'll tell you which package to restore to get your keyboard back.

You can also run UAD and try to see if it succeed to list all the packages.

If you have an authorization error this means your phone is waiting for you to authorize the ADB connection. As you can't unlock your phone, you only have to do a factory reset.

**Factory reset**: You can perform a factory reset without unlocking your phone by booting to the recovery. [Here are the steps](https://www.motorola-support.com/us-en/?page=device/motorola/moto-g7-play/topic/reset/external-reset/1)

I hope you backed-up important data in the case you have to factory reset your phone.

Good luck!

**Comment by kcstandefer** [comment]
I'm super tech savvy, just not about phones.  I've been  a software
developer my whole career.  The instructions you sent me were 1) in French
and 2) wrong.  But, I did get the phone reset, which is all I wanted.  This
was a project phone, not my main phone.  And, I'm selling it, so no harm.

**Comment by 0x192** [comment]
> I'm super tech savvy, just not about phones. I've been a software developer my whole career.

Well... my bad! To be honest, I would have thought that a software developer would have followed the warning message before using an alpha software.

> The instructions you sent me were 1) in French

Sorry for the french webpage. I don't know how I messed up. I wanted to post the english version.

> and 2) wrong

Wrong? I managed to find the official documentation and Morotola [says the exact same thing](https://www.motorola-support.com/us-en/?page=device/motorola/moto-g7-play/topic/reset/external-reset/8).

>  This was a project phone, not my main phone.

And this was a wise decision given the results :roll_eyes:


Hopefully you will have a better experience with next releases. The `v0.4` is about to be released.

**Comment by kcstandefer** [comment]
The part that is wrong is that after you select "Recovery", you get a page
that says "No command".  You have to press the power button and the up
volume button to get to the page that has the Factory Reset selection from
the No Command screen.    then, there are several other choices you have to
make to get the reset done.  Here are the correct instructions (and yes,
they are wrong on the Motorola site):

https://www.att.com/device-support/article/wireless/KM1384282/Motorola/MotorolaXT19525

**Comment by 0x192** [comment]
Thanks for the correction!
